model_name: "output_transform_test_model"

centering:
  my_center: 3

output_transform_test_model:
  intercepts:
    baseline: 10 # This will be our initial 'result'
  coefficients: {} # No direct coefficients for simplicity
  transformations: [] # No transformations for simplicity
  factors: [] # No factors for simplicity
  conditions: [] # No conditions for simplicity

  # We will vary output_transformation in tests by loading and modifying this config
  output_transformation: "add_value(result, 0)" # Default: no-op via function call
